volumes:
  db-product-data:
  db-currency-data:
  db-user-data:
  db-order-data:
  db-cart-data:


services:

  # -------------------------------
  discovery-service:
    image: discovery-service:latest
    build:
      context: ./discovery-service
    ports:
      - "8761:8761"
    environment:
     EUREKA_INSTANCE_HOSTNAME: config-service
    
  # -------------------------------
  config-service:
    image: config-service:latest
    build:
      context: ./config-service
    depends_on:
      - discovery-service
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
      EUREKA_INSTANCE_HOSTNAME: config-service
  
  # -------------------------------
  greeting-service:
    image: greeting-service:latest
    build:
      context: ./greeting-service
    depends_on:
      - discovery-service
      - config-service
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-service:8888
      EUREKA_INSTANCE_HOSTNAME: greeting-service

  # -------------------------------
  db-currency:
    image: postgres:16
    environment:
      POSTGRES_DB: db_currency
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - db-currency-data:/var/lib/postgresql/data
      
  currency-service:
    image: currency-service:latest
    build:
      context: ./currency-service
    depends_on:
      - discovery-service
      - db-currency
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-currency:5432/db_currency
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "false"
      EUREKA_INSTANCE_HOSTNAME: currency-service
    
  # -------------------------------
  db-product:
    image: postgres:16
    environment:
      POSTGRES_DB: db_product
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - db-product-data:/var/lib/postgresql/data
    
  product-service:
    image: product-service:latest
    build:
      context: ./product-service
    depends_on:
      - discovery-service
      - db-product
      - currency-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-product:5432/db_product
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
      EUREKA_INSTANCE_HOSTNAME: product-service
  # -------------------------------
  db-user:
    image: postgres:16
    environment:
      POSTGRES_DB: db_user
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - db-user-data:/var/lib/postgresql/data
    
  auth-service:
    image: auth-service:latest
    build:
     context: ./auth-service/auth-service
     dockerfile: Dockerfile
    depends_on:
      - discovery-service
      - db-user
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-user:5432/db_user
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
      EUREKA_INSTANCE_HOSTNAME: auth-service
    
  # -------------------------------
  db-order:
    image: postgres:16
    environment:
      POSTGRES_DB: db_order
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - db-order-data:/var/lib/postgresql/data
    
  order-service:
    image: order-service:latest
    build:
      context: ./order-service
    depends_on:
      - discovery-service
      - db-order
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-order:5432/db_order
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
      EUREKA_INSTANCE_HOSTNAME: order-service
    
  # -------------------------------
  gateway-service:
    image: gateway-service:latest
    build:
      context: ./gateway-service
    ports:
      - "8765:8765"
    depends_on:
      - discovery-service
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
      EUREKA_INSTANCE_HOSTNAME: gateway-service
    
# -------------------------------
  db-cart:
    image: postgres:16
    environment:
      POSTGRES_DB: db_cart
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - db-cart-data:/var/lib/postgresql/data
    
  cart-service:
    image: cart-service:latest
    build:
      context: ./cart-service
    depends_on:
      - discovery-service
      - db-cart
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-cart:5432/db_cart
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
      EUREKA_INSTANCE_HOSTNAME: cart-service
  email-service:
    image: email-service:latest
    build:
      context: ./email-service
    depends_on:
      - discovery-service
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-service:8888
      EUREKA_INSTANCE_HOSTNAME: email-service

  maps-service:
    image: maps-service:latest
    build:
      context: ./maps-service
    depends_on:
      - discovery-service
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-service:8888
      EUREKA_INSTANCE_HOSTNAME: maps-service